"""empty message

Revision ID: 23e3a02ba46b
Revises: 
Create Date: 2018-11-02 16:52:43.842738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23e3a02ba46b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('grade_number', sa.Integer(), nullable=True),
    sa.Column('family_type', sa.String(length=50), nullable=True),
    sa.Column('child_number', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('family_history', sa.String(length=800), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aptitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_info_id', sa.Integer(), nullable=True),
    sa.Column('aptitudes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['person_info_id'], ['person_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('person_info_id', sa.Integer(), nullable=True),
    sa.Column('symptoms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['person_info_id'], ['person_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptoms')
    op.drop_table('aptitudes')
    op.drop_table('person_info')
    op.drop_table('person')
    # ### end Alembic commands ###
